### ISSUE TITLE
Feature Request: Is it possible to set the ui5 url as an parameter?

### ISSUE THREAD

**Issue by hauntedhill** [kennyzhangdev/ui5depchk#1]
Hi,

i have no direct internet connection in my environment. Because of that the quest:

The URL of the sapui5 api-index-depricated.json is hard coded in ui5depchk/plugin/lib/index.js line 29 and no- deprecared-api.js line 43. Is it possible to replace this string by a parameter? For example to replace the url by a custom url: https://localhost:8080/docs/api/api-index-deprecated.json.

Thank you.

Regards

Haunted

**Comment by kennyzhangdev** [comment]
Hi Haunted,

Sorry for the late reply as I missed this message in email.

In Version 0.4.0, I added an optional parameter **ui5DepreacatedURL** in .eslintrc.
Example:
"rules": {
    "ui5depchk/no-deprecated-api": [
      "warn",
      {
        "ui5version": "1.84",
        "ui5DepreacatedURL": "https://ui5.sap.com/docs/api/api-index-deprecated.json"
      }
    ]
  }
Replace it with your own URL.

Kind regards,

Kenny
